import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Container from '@/components/layouts/Container';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Nextshop App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${roboto.variable} antialiased`}>
    <Container>
      {children}
    </Container>
    </body>
    </html>
  );
}
